### ISSUE TITLE
Infografía de Hilos

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/infografia-de-hilos-Daniel-Velasco-Lopez#2]
[Infografía de hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Daniel-Velasco-Lopez/files/15044511/Infografia.de.hilos.pdf)

Daniel Velasco López

**Comment by Ariadnamonserrat10** [comment]
Calificación
18 de 20 por que el color de los cuadros de texto dificulta su lectura

**Comment by Ariadnamonserrat10** [comment]
Calificación
19 de 20 solamente por que esta un poco desorganizado

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
